Library/urls.py
from django.urls import path
from .views import *

app_name = 'library'

urlpatterns = [
    path('' , IndexView.as_view() , name='main'),
    path('search', SearchBookView.as_view(), name='search'),
    path('search_user', SearchUserView.as_view(), name='search_user'),
    path('search_borrowing', SearchBorrowingView.as_view(), name='search_borrowing'),
    #book
    path('create_book', CreateBookView.as_view(), name='add_book'),
    path('book_detail/<int:pk>', BookDetailView.as_view(), name='book_detail'),
    path('book_edite/<int:pk>', book_edite, name='book_edite'),
    path('book/delete/<int:pk>' , BookDelete.as_view() , name='book_delete'),
    path('browssing_book', BrowssingView.as_view(), name='briwssing_book'),
    path('browssing_book/add', BrowssingFormView.as_view(), name='briwssing_form_book'),
    path('borrowing/delete/<int:pk>' , BorrowingDelete.as_view() , name='borrowing_delete'),
    #user
    path('create_user' , CreateUserView.as_view() , name='add_user'),
    path('user_detail/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('user_edite/<int:pk>', user_edite, name='user_edite'),
    path('user/delete/<int:pk>' , UserDelete.as_view() , name='user_delete')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('ckeditor/' , include('ckeditor_uploader.urls')),
    path("admin/", admin.site.urls),
    path("" , include('Library.urls')),
    path("account/" , include('account.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Library/models.py
from typing import Iterable
from django.db import models
from account.models import User
from persiantools.jdatetime import JalaliDate
from django.utils.text import slugify

class Type(models.Model):
    title = models.CharField(max_length=350 , null=True , verbose_name='نوع کتاب')
    created = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'نوع کتاب'
        verbose_name_plural = 'نوع کتاب ها'

class Leason(models.Model):
    title = models.CharField(max_length=350 , null=True , verbose_name='نام درس')
    created = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'درس'
        verbose_name_plural = 'درس ها'

class Category(models.Model):
    title = models.CharField(max_length=250 , null=True , verbose_name='نام دسته بندی')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'


class Book(models.Model):
    title = models.CharField(max_length=250 , null=True , verbose_name='نام کتاب')
    content = models.TextField(null=True , verbose_name='توضیحات')
    created_at = models.IntegerField(null=True , verbose_name='سال انتشار')
    category = models.ManyToManyField(Category , related_name='books_category' , null=True , verbose_name='نوع کتاب')
    leason = models.ForeignKey(Leason , on_delete=models.CASCADE , related_name='books_leason' , null=True , verbose_name='درس')
    type = models.ManyToManyField(Type , related_name='books_type' , null=True , verbose_name=' سطح')
    publisher = models.CharField(max_length=450 , null=True , verbose_name='ناشر')
    the_author = models.TextField(null=True , verbose_name='مولفان')
    educational_base = models.CharField(max_length=350 , null=True , verbose_name='پایه تحصیلی')
    users = models.ManyToManyField(User , related_name='books_user' , null=True , verbose_name='کاربران')
    image = models.FileField(upload_to='book/image' , blank=True , null=True , verbose_name='تصویر کتاب')  
    status = models.BooleanField(default=True , verbose_name='موجودی')
    browssing = models.BooleanField(default=False , verbose_name='امانت')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}--{self.educational_base}--{self.leason.title}--{self.publisher}'
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'کتاب'
        verbose_name_plural = 'کتاب ها '

    def get_jalali_date(self):
        return JalaliDate(self.created, locale=('fa')).strftime("%c")
    
class Borrowingbook(models.Model):
    full_name = models.CharField(max_length=550 , null=True , blank=True , verbose_name='نام و نام خانوادگی')
    phone_number = models.CharField(max_length=550 , null=True , blank=True , verbose_name='شماره تلفن')
    # book = models.CharField(max_length=550 , null=True , blank=True , verbose_name='کتاب امانت گرفته شده')
    book = models.ManyToManyField(Book , related_name='rents' , null=True , blank=True , verbose_name='کتاب')
    expiration_date = models.DateTimeField(null=True , blank=True , verbose_name='تاریخ انقضا')
    date_added = models.DateTimeField(auto_now_add=True , verbose_name='تاریخ تولید')

    def __str__(self) -> str:
        return f'{self.full_name}--{self.phone_number}'

    class Meta:
        ordering = ('-date_added',)
        verbose_name = 'امانت'
        verbose_name_plural = 'امانت ها '

    def get_jalali_date(self):
        return JalaliDate(self.date_added , self.expiration_date , locale=('fa')).strftime("%c")

Library/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core import validators
from account.models import User
from .models import *

class CreateBookForm(forms.ModelForm):
    class Meta:
        model= Book
        fields=('title' , 'content' , 'created_at' , 'publisher' , 'the_author', 'educational_base' , 'category' , 'leason' , 'type' , 'users' , 'image')
        widgets={
            'title':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' نام کتاب' , 'style':'text-align: right!important;'}),
            'content':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' توضیحات' , 'style':'text-align: right!important;'}),
            'created_at':forms.NumberInput(attrs={'class': 'form-control' , 'placeholder':'سال انتشار' , 'style':'text-align: right!important;'}),
            'publisher':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' منتشر کننده' , 'style':'text-align: right!important;'}),
            'the_author':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' مولفان' , 'style':'text-align: right!important;'}),
            'educational_base':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' پایه تحصیلی' , 'style':'text-align: right!important;'}),
            # 'category':forms.ModelMultipleChoiceField(queryset=Category.objects.all() , widget=forms.CheckboxSelectMultiple),
            # 'leason':forms.ModelMultipleChoiceField(queryset=Leason.objects.all() , widget=forms.CheckboxSelectMultiple),
            # 'type':forms.ModelMultipleChoiceField(queryset=Type.objects.all() , widget=forms.CheckboxSelectMultiple),
            'publisher':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' منتشر کننده' , 'style':'text-align: right!important;'}),
            # 'users':forms.ModelMultipleChoiceField(queryset=User.objects.all() , widget=forms.CheckboxSelectMultiple),
        }

class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('phone_number' , 'username' , 'full_name' , 'email' , 'password' , 'password_copy')
        widgets={
            'phone_number':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' شماره تلفن' , 'style':'text-align: right!important;'}),
            'password':forms.PasswordInput(attrs={'class': 'form-control' , 'placeholder':' پسورد ' , 'style':'text-align: right!important;'}),
            'password_copy':forms.PasswordInput(attrs={'class': 'form-control' , 'placeholder':'  تکرار پسورد ' , 'style':'text-align: right!important;'}),
            'username':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':' نام کاربری' , 'style':'text-align: right!important;'}),
            'full_name':forms.TextInput(attrs={'class': 'form-control' , 'placeholder':'نام کامل' , 'style':'text-align: right!important;'}),
            'email':forms.EmailInput(attrs={'class': 'form-control' , 'placeholder':' ایمیل' , 'style':'text-align: right!important;'}),
        }

Library/views.py
from typing import Any
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import TemplateView , ListView , FormView , UpdateView , DetailView , View
from django.db.models import Q
from Library.models import Book , Borrowingbook
from account.models import User
from .forms import CreateBookForm , CreateUserForm

class IndexView(TemplateView):
    template_name = 'Library/index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = Book.objects.all()
        context['users'] = User.objects.all()
        context['browsing_book'] = Borrowingbook.objects.all()
        context['borrowing_books'] = Book.objects.filter(browssing=True)
        return context

class SearchBookView(ListView):
    template_name = 'Library/search-result.html'
    model = Book
    paginate_by = 15
    context_object_name = 'books'
    def get_queryset(self):
        q = self.request.GET.get('q')
        return Book.objects.filter(
            Q(title__icontains=q) | Q(content__icontains=q) | Q(created_at__icontains=q) | Q(publisher__icontains=q) | Q(educational_base__icontains=q))

class SearchUserView(ListView):
    template_name = 'Library/search-user-result.html'
    model = User
    paginate_by = 15
    context_object_name = 'users'
    def get_queryset(self):
        q = self.request.GET.get('q2')
        return User.objects.filter(
            Q(phone_number__icontains=q) | Q(username__icontains=q) | Q(email__icontains=q) | Q(full_name__icontains=q))
    
class SearchBorrowingView(ListView):
    template_name = 'Library/search-result-borrowing.html'
    model = User
    paginate_by = 15
    context_object_name = 'browsing_book'
    def get_queryset(self):
        q = self.request.GET.get('q3')
        return User.objects.filter(
            Q(full_name__icontains=q) | Q(phone_number__icontains=q))
    

class CreateBookView(FormView):
    template_name = 'Library/add_book.html'
    form_class = CreateBookForm
    success_url = 'library:main'
    def form_valid(self , form):
        cd = form.cleaned_data
        form.save()
        return redirect(reverse('library:main'))

class BookDetailView(DetailView):
    template_name = 'Library/book-detail.html'
    model = Book
    context_object_name = 'book'

def book_edite(request , pk):
    if request.user.is_authenticated == True:
        user = request.user
        book = get_object_or_404(Book , pk=pk)
        form = CreateBookForm(instance=book)
        if request.method == 'POST':
            form = CreateBookForm(request.POST  , request.FILES , instance=book)
            if form.is_valid():
                form.save()
                return redirect('library:main')
        else:
            form = CreateBookForm(instance=book)
        return render(request , 'Library/book-edite.html' , {'form':form})
    else:
        return redirect('library:main')
    
class BookDelete(View):
    def get(self , request , pk):
        book = get_object_or_404(Book , pk=pk)
        book.delete()
        return redirect('library:main')
     
class CreateUserView(FormView):
    template_name = 'Library/add_user.html'
    form_class = CreateUserForm
    success_url = 'library:main'
    def form_valid(self , form):
        cd = form.cleaned_data
        form.save()
        return redirect(reverse('library:main'))

class UserDetailView(DetailView):
    template_name = 'Library/user-detail.html'
    model = User
    context_object_name = 'user'

def user_edite(request , pk):
    if request.user.is_authenticated == True:
        user = get_object_or_404(User , pk=pk)
        form = CreateUserForm(instance=user)
        if request.method == 'POST':
            form = CreateUserForm(request.POST  , request.FILES , instance=user)
            if form.is_valid():
                form.save()
                return redirect('library:main')
        else:
            form = CreateUserForm(instance=user)
        return render(request , 'Library/user-edite.html' , {'form':form})
    else:
        return redirect('library:main')

class UserDelete(View):
    def get(self , request , pk):
        user = get_object_or_404(User , pk=pk)
        user.delete()
        return redirect('library:main')
    
class BrowssingView(View):
    template_name = 'Library/briwssing_book.html'
    def get(self , request):
        books = Book.objects.filter(browssing=False)
        return render(self.request , self.template_name , {'books':books})

class BrowssingFormView(View):
    template_name = 'Library/briwssing_book.html'
    def post(self , request):
        full_name = request.POST.get('full_name')
        phone_number = request.POST.get('phone_number')
        book = request.POST.get('book')
        expiration_date = request.POST.get('expiration_date')
        books = Book.objects.all()
        for x in books:
            book_name = f'{x.title}--{x.educational_base}--{x.leason.title}--{x.publisher}'
            if book_name == book:
                print(x)
                x.browssing == True
                y=x
        book = Borrowingbook.objects.create(full_name=full_name , phone_number=phone_number , expiration_date=expiration_date)
        book.book.add(y)
        return redirect('library:main')
    
class BorrowingDelete(View):
    def get(self , request , pk):
        book = get_object_or_404(Borrowingbook , pk=pk)
        book.delete()
        return redirect('library:main')

Library/templates/Library/book-detail.html
{% extends 'base.html' %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <br><br>
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                  <!-- Box Comment -->
                  <div class="card card-widget">
                    <div class="card-header">
                      <div class="user-block">
                        <img class="img-circle" src="{{book.image.url}}" alt="User Image">
                        <span class="username"><a href="#">{{book.title}}</a></span>
                        <span class="description">{{book.created}}</span>
                      </div>
                      <!-- /.user-block -->
                      <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
                          <i class="fa fa-circle-o"></i></button>
                        <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                        </button>
                      </div>
                      <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <!-- post text -->
                      <label for="p">توضیحات</label>
                      <p>{{book.content}}</p>
                      <label for="p">سال انتشار</label>
                      <p>{{book.created_at}}</p>
                      <label for="p"> منتشر کننده</label>
                      <p>{{book.publisher}}</p>
                      <label for="p"> مولفان</label>
                      <p>{{book.the_author}}</p>
                      <label for="p"> دسته بندی</label>
                      {% for cate in book.category.all %}
                      <p>{{cate.title}}</p>
                      {% endfor %}
                      <label for="p"> درس</label>
                      <p>{{book.leason.title}}</p>
                      <label for="p"> سطح</label>
                      {% for type in book.type.all %}
                      <p>{{type.title}}</p>
                      {% endfor %}
                      <label for="p"> پایه تحصیلی</label>
                      <p>{{book.educational_base}}</p>
                      <label for="p"> کاربرها</label>
                      {% for user in book.users.all %}
                      <p>{{user.phone_number}}</p>
                      {% endfor %}
                      <!-- Social sharing buttons -->
                      <!-- <button type="button" class="btn btn-default btn-sm"><i class="fa fa-share"></i> اشتراک گذاری</button>
                      <button type="button" class="btn btn-default btn-sm"><i class="fa fa-thumbs-o-up"></i> لایک</button> -->
                      <a href="{% url 'library:book_delete' book.id %}">
                          <button type="button" class="btn btn-block btn-outline-warning btn-sm">حذف</button>
                      </a>
                    </div>
                  </div>
                  <!-- /.card -->
                </div>
              </div>
              <!-- /.row -->
        </div>
    </section>
    </div>
    <!-- /.content-wrapper -->
{% endblock %}

Library/templates/Library/search-result-borrowing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">داشبورد</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="#">خانه</a></li>
            <li class="breadcrumb-item active">داشبورد</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <!-- /.card -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">امانت گیرنده ها</h3>
                            <br>
                            <a class="btn btn-app" href="{% url 'library:briwssing_book' %}">
                                <i class="fa fa-inbox"></i> امانت گیرنده ها
                            </a>
                            <br>
                            <div class="card-tools">
                            <form method="GET" action="{% url "library:search_borrowing" %}" >
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="q3" class="form-control float-right" placeholder="جستجو" value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}" required>
            
                                <div class="input-group-append">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover">
                            <tr>
                                <th>نام و نام خانوادگی</th>
                                <th>شماره تلفن</th>
                                <th>نام کتاب</th>
                                <th>تاریخ</th>
                            </tr>
                            {% for x in browsing_book %}
                            <tr>
                                <td>{{x.full_name}}</td>
                                <td>{{x.phone_number}}</td>
                                <td>
                                    {% for y in x.book.all %}
                                    {{y.title}}
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'library:borrowing_delete' x.id %}">
                                        <button type="button" class="btn btn-block btn-outline-warning btn-sm">حذف</button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </table>
                        </div>
                        <!-- /.card-body -->
                        <!-- /.card-body -->
                    </div>
                </div>
            </div><!-- /.row -->
            <!-- /.card -->
    </div>
    <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock %}

Library/templates/Library/search-result.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">داشبورد</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-left">
            <li class="breadcrumb-item"><a href="#">خانه</a></li>
            <li class="breadcrumb-item active">داشبورد</li>
        </ol>
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <!-- /.card -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">کتاب ها</h3>
        
                        <div class="card-tools">
                            <form method="GET" action="{% url "library:search" %}" >
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="q" class="form-control float-right" placeholder="جستجو" value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}" required>
                
                                    <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <table class="table table-hover">
                        <tr>
                            <th>کتاب</th>
                            <th>ناشر</th>
                            <th>سال</th>
                            <th>دسته بندی</th>
                            <th>درس</th>
                            <th>سطح</th>
                            <th>پایه</th>
                            <th>وضعیت</th>
                            <th>توضیحات</th>
                        </tr>
                        {% for book in books %}
                        <tr>
                            <td>
                                <img src="{{book.image.url}}" alt="Product 1" class="img-circle img-size-32 mr-2">
                                {{book.title}}
                            </td>
                            <td>{{book.publisher}}</td>
                            <td>{{book.created_at}}</td>
                            <td>
                                {% for cate in book.category.all %}
                                --{{cate.title}}
                                {% endfor %}
                            </td>
                            <td>{{book.leason.title}}</td>
                            <td>
                                {% for ty in book.type.all %}
                                --{{ty.title}}
                                {% endfor %}
                            </td>
                            <td>{{book.educational_base}}</td>
                            {% if book.status %}
                            <td><span class="badge badge-success">تایید شده</span></td>
                            {% else %}
                            <td><span class="badge badge-success">لغو شده</span></td>
                            {% endif %}
                            <td>{{book.content}}</td>
                        </tr>
                        {% endfor %}
                        </table>
                    </div>
                    <!-- /.card-body -->
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">کاربر ها</h3>
            
                            <div class="card-tools">
                            <form method="GET" action="{% url "library:search_user" %}" >
                                <div class="input-group input-group-sm" style="width: 150px;">
                                    <input type="text" name="q" class="form-control float-right" placeholder="جستجو" value="{% if request.GET.q %}{{ request.GET.q }}{% endif %}" required>
                
                                    <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0">
                            <table class="table table-hover">
                            <tr>
                                <th>تلفن همراه</th>
                                <th>نام کاربری</th>
                                <th>ایمیل</th>
                                <th>نام کامل</th>
                                <th>مدرس</th>
                                <th>ادمین</th>
                                <th>فعال</th>
                            </tr>
                            {% for user in users %}
                            <tr>
                                <td>
                                    {{user.phone_number}}
                                </td>
                                <td>{{user.username}}</td>
                                <td>{{user.email}}</td>
                                <td>
                                    {{user.full_name}}
                                </td>
                                {% if user.is_staff %}
                                <td><span class="badge badge-success">تایید شده</span></td>
                                {% else %}
                                <td><span class="badge badge-success">لغو شده</span></td>
                                {% endif %}
                                {% if user.is_admin %}
                                <td><span class="badge badge-success">تایید شده</span></td>
                                {% else %}
                                <td><span class="badge badge-success">لغو شده</span></td>
                                {% endif %}
                                {% if user.active %}
                                <td><span class="badge badge-success">تایید شده</span></td>
                                {% else %}
                                <td><span class="badge badge-success">لغو شده</span></td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
            </div><!-- /.row -->
            <!-- /.card -->
    </div>
    <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->
{% endblock %}